import type { ShortcutDisplayMode, ShortcutGroupLayout, ShortcutKind, ShortcutSurface } from "./types.js";

export interface ShortcutGroupSeed {
  id: string;
  title: string;
  icon: string;
  description: string;
  layout: ShortcutGroupLayout;
  surface: ShortcutSurface;
  sortOrder: number;
}

export interface ShortcutSeed {
  id: string;
  groupId: string;
  title: string;
  detail: string;
  kind: ShortcutKind;
  value: string;
  dangerous?: boolean;
  actionKey?: string;
  displayMode?: ShortcutDisplayMode;
  sortOrder?: number;
}

export const DEFAULT_SHORTCUT_GROUPS: readonly ShortcutGroupSeed[] = [
  { id: "favorites", title: "收藏", icon: "☆", description: "按操作次数显示最常用的 8 个快捷键", layout: "grid", surface: "palette", sortOrder: 0 },
  { id: "tmux", title: "Tmux", icon: ">_", description: "tmux 会话操作", layout: "grid", surface: "palette", sortOrder: 1 },
  { id: "codex", title: "Codex", icon: "✳", description: "Codex 命令", layout: "grid", surface: "palette", sortOrder: 2 },
  { id: "ctrl", title: "Ctrl", icon: "⌃", description: "终端控制键", layout: "grid", surface: "palette", sortOrder: 3 },
  { id: "keyboard", title: "键盘", icon: "⌨", description: "特殊键和组合键", layout: "keyboard", surface: "palette", sortOrder: 4 },
  { id: "composer", title: "输入框快捷键", icon: "↔", description: "输入框下方的操作按钮", layout: "grid", surface: "composer", sortOrder: 5 },
];

const DEFAULT_TMUX_SHORTCUTS: readonly ShortcutSeed[] = [
  { id: "tmux-send-prefix", title: "^b, ^b", detail: "发送前缀键", groupId: "tmux", kind: "terminal", value: "tmux-send-prefix" },
  { id: "tmux-rotate-pane", title: "^b, ^o", detail: "轮换窗格", groupId: "tmux", kind: "terminal", value: "tmux-rotate-pane" },
  { id: "tmux-suspend", title: "^b, ^z", detail: "挂起客户端", groupId: "tmux", kind: "terminal", value: "tmux-suspend" },
  { id: "tmux-break-pane", title: "^b, !", detail: "拆出窗格", groupId: "tmux", kind: "terminal", value: "tmux-break-pane" },
  { id: "tmux-split-horizontal", title: "^b, \"", detail: "上下分割窗格", groupId: "tmux", kind: "terminal", value: "tmux-split-horizontal" },
  { id: "tmux-list-buffers", title: "^b, #", detail: "查看粘贴缓冲区", groupId: "tmux", kind: "terminal", value: "tmux-list-buffers" },
  { id: "tmux-rename-session", title: "^b, $", detail: "重命名 Session", groupId: "tmux", kind: "terminal", value: "tmux-rename-session" },
  { id: "tmux-split-vertical", title: "^b, %", detail: "左右分割窗格", groupId: "tmux", kind: "terminal", value: "tmux-split-vertical" },
  { id: "tmux-kill-window", title: "^b, &", detail: "关闭当前窗口", groupId: "tmux", kind: "terminal", value: "tmux-kill-window", dangerous: true },
  { id: "tmux-select-window-prompt", title: "^b, '", detail: "按编号选择窗口", groupId: "tmux", kind: "terminal", value: "tmux-select-window-prompt" },
  { id: "tmux-previous-session", title: "^b, (", detail: "上一个 Session", groupId: "tmux", kind: "terminal", value: "tmux-previous-session" },
  { id: "tmux-next-session", title: "^b, )", detail: "下一个 Session", groupId: "tmux", kind: "terminal", value: "tmux-next-session" },
  { id: "tmux-new-floating-pane", title: "^b, *", detail: "新建浮动窗格", groupId: "tmux", kind: "terminal", value: "tmux-new-floating-pane" },
  { id: "tmux-rename-window", title: "^b, ,", detail: "重命名窗口", groupId: "tmux", kind: "terminal", value: "tmux-rename-window" },
  { id: "tmux-delete-buffer", title: "^b, -", detail: "删除最近缓冲区", groupId: "tmux", kind: "terminal", value: "tmux-delete-buffer" },
  { id: "tmux-move-window-prompt", title: "^b, .", detail: "移动窗口编号", groupId: "tmux", kind: "terminal", value: "tmux-move-window-prompt" },
  { id: "tmux-window-0", title: "^b, 0", detail: "窗口 0", groupId: "tmux", kind: "terminal", value: "tmux-window-0" },
  { id: "tmux-window-3", title: "^b, 3", detail: "窗口 3", groupId: "tmux", kind: "terminal", value: "tmux-window-3" },
  { id: "tmux-window-4", title: "^b, 4", detail: "窗口 4", groupId: "tmux", kind: "terminal", value: "tmux-window-4" },
  { id: "tmux-window-5", title: "^b, 5", detail: "窗口 5", groupId: "tmux", kind: "terminal", value: "tmux-window-5" },
  { id: "tmux-window-6", title: "^b, 6", detail: "窗口 6", groupId: "tmux", kind: "terminal", value: "tmux-window-6" },
  { id: "tmux-window-7", title: "^b, 7", detail: "窗口 7", groupId: "tmux", kind: "terminal", value: "tmux-window-7" },
  { id: "tmux-window-8", title: "^b, 8", detail: "窗口 8", groupId: "tmux", kind: "terminal", value: "tmux-window-8" },
  { id: "tmux-window-9", title: "^b, 9", detail: "窗口 9", groupId: "tmux", kind: "terminal", value: "tmux-window-9" },
  { id: "tmux-command-prompt", title: "^b, :", detail: "打开 tmux 命令行", groupId: "tmux", kind: "terminal", value: "tmux-command-prompt" },
  { id: "tmux-last-pane", title: "^b, ;", detail: "上一个窗格", groupId: "tmux", kind: "terminal", value: "tmux-last-pane" },
  { id: "tmux-choose-buffer", title: "^b, =", detail: "选择粘贴缓冲区", groupId: "tmux", kind: "terminal", value: "tmux-choose-buffer" },
  { id: "tmux-list-keys", title: "^b, ?", detail: "查看所有快捷键", groupId: "tmux", kind: "terminal", value: "tmux-list-keys" },
  { id: "tmux-detach-client", title: "^b, D", detail: "选择客户端并断开", groupId: "tmux", kind: "terminal", value: "tmux-detach-client" },
  { id: "tmux-last-session", title: "^b, L", detail: "返回上一个 Session", groupId: "tmux", kind: "terminal", value: "tmux-last-session" },
  { id: "tmux-copy-mode", title: "^b, [", detail: "进入复制模式", groupId: "tmux", kind: "terminal", value: "tmux-copy-mode" },
  { id: "tmux-paste-buffer", title: "^b, ]", detail: "粘贴最近缓冲区", groupId: "tmux", kind: "terminal", value: "tmux-paste-buffer" },
  { id: "tmux-find-window", title: "^b, f", detail: "搜索窗口文本", groupId: "tmux", kind: "terminal", value: "tmux-find-window" },
  { id: "tmux-display-window-info", title: "^b, i", detail: "显示窗口信息", groupId: "tmux", kind: "terminal", value: "tmux-display-window-info" },
  { id: "tmux-last-window", title: "^b, l", detail: "返回上一个窗口", groupId: "tmux", kind: "terminal", value: "tmux-last-window" },
  { id: "tmux-mark-pane", title: "^b, m", detail: "标记当前窗格", groupId: "tmux", kind: "terminal", value: "tmux-mark-pane" },
  { id: "tmux-clear-mark", title: "^b, M", detail: "清除窗格标记", groupId: "tmux", kind: "terminal", value: "tmux-clear-mark" },
  { id: "tmux-display-pane-index", title: "^b, q", detail: "显示窗格编号", groupId: "tmux", kind: "terminal", value: "tmux-display-pane-index" },
  { id: "tmux-refresh-client", title: "^b, r", detail: "刷新客户端", groupId: "tmux", kind: "terminal", value: "tmux-refresh-client" },
  { id: "tmux-choose-session", title: "^b, s", detail: "选择 Session", groupId: "tmux", kind: "terminal", value: "tmux-choose-session" },
  { id: "tmux-display-time", title: "^b, t", detail: "显示时间", groupId: "tmux", kind: "terminal", value: "tmux-display-time" },
  { id: "tmux-set-pane-title", title: "^b, T", detail: "设置窗格标题", groupId: "tmux", kind: "terminal", value: "tmux-set-pane-title" },
  { id: "tmux-kill-pane", title: "^b, x", detail: "关闭当前窗格", groupId: "tmux", kind: "terminal", value: "tmux-kill-pane", dangerous: true },
  { id: "tmux-choose-tree", title: "^b, Tab", detail: "模糊选择窗口和 Session", groupId: "tmux", kind: "terminal", value: "tmux-choose-tree" },
  { id: "tmux-swap-pane-up", title: "^b, {", detail: "与上一个窗格交换", groupId: "tmux", kind: "terminal", value: "tmux-swap-pane-up" },
  { id: "tmux-swap-pane-down", title: "^b, }", detail: "与下一个窗格交换", groupId: "tmux", kind: "terminal", value: "tmux-swap-pane-down" },
  { id: "tmux-floating-g1", title: "^b, g 1", detail: "浮动窗格移到左上", groupId: "tmux", kind: "terminal", value: "tmux-floating-g1" },
  { id: "tmux-floating-g2", title: "^b, g 2", detail: "浮动窗格移到右上", groupId: "tmux", kind: "terminal", value: "tmux-floating-g2" },
  { id: "tmux-floating-g3", title: "^b, g 3", detail: "浮动窗格移到左下", groupId: "tmux", kind: "terminal", value: "tmux-floating-g3" },
  { id: "tmux-floating-g4", title: "^b, g 4", detail: "浮动窗格移到右下", groupId: "tmux", kind: "terminal", value: "tmux-floating-g4" },
  { id: "tmux-floating-up", title: "^b, g ↑", detail: "浮动窗格移到上边", groupId: "tmux", kind: "terminal", value: "tmux-floating-up" },
  { id: "tmux-floating-down", title: "^b, g ↓", detail: "浮动窗格移到下边", groupId: "tmux", kind: "terminal", value: "tmux-floating-down" },
  { id: "tmux-floating-left", title: "^b, g ←", detail: "浮动窗格移到左边", groupId: "tmux", kind: "terminal", value: "tmux-floating-left" },
  { id: "tmux-floating-right", title: "^b, g →", detail: "浮动窗格移到右边", groupId: "tmux", kind: "terminal", value: "tmux-floating-right" },
  { id: "tmux-show-messages", title: "^b, ~", detail: "查看 tmux 消息", groupId: "tmux", kind: "terminal", value: "tmux-show-messages" },
  { id: "tmux-copy-mode-page-up", title: "^b, PgUp", detail: "复制模式向上翻页", groupId: "tmux", kind: "terminal", value: "tmux-copy-mode-page-up" },
  { id: "tmux-select-pane-up", title: "^b, ↑", detail: "选择上方窗格", groupId: "tmux", kind: "terminal", value: "tmux-select-pane-up" },
  { id: "tmux-select-pane-down", title: "^b, ↓", detail: "选择下方窗格", groupId: "tmux", kind: "terminal", value: "tmux-select-pane-down" },
  { id: "tmux-select-pane-left", title: "^b, ←", detail: "选择左侧窗格", groupId: "tmux", kind: "terminal", value: "tmux-select-pane-left" },
  { id: "tmux-select-pane-right", title: "^b, →", detail: "选择右侧窗格", groupId: "tmux", kind: "terminal", value: "tmux-select-pane-right" },
  { id: "tmux-layout-m1", title: "^b, M-1", detail: "even-horizontal 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m1" },
  { id: "tmux-layout-m2", title: "^b, M-2", detail: "even-vertical 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m2" },
  { id: "tmux-layout-m3", title: "^b, M-3", detail: "main-horizontal 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m3" },
  { id: "tmux-layout-m4", title: "^b, M-4", detail: "main-horizontal-mirrored 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m4" },
  { id: "tmux-layout-m5", title: "^b, M-5", detail: "main-vertical 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m5" },
  { id: "tmux-layout-m6", title: "^b, M-6", detail: "main-vertical-mirrored 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m6" },
  { id: "tmux-layout-m7", title: "^b, M-7", detail: "tiled 布局", groupId: "tmux", kind: "terminal", value: "tmux-layout-m7" },
  { id: "tmux-next-layout", title: "^b, Space", detail: "切换下一个布局", groupId: "tmux", kind: "terminal", value: "tmux-next-layout" },
  { id: "tmux-next-alert-window", title: "^b, M-n", detail: "下一个活动窗口", groupId: "tmux", kind: "terminal", value: "tmux-next-alert-window" },
  { id: "tmux-rotate-pane-backward", title: "^b, M-o", detail: "反向轮换窗格", groupId: "tmux", kind: "terminal", value: "tmux-rotate-pane-backward" },
  { id: "tmux-previous-alert-window", title: "^b, M-p", detail: "上一个活动窗口", groupId: "tmux", kind: "terminal", value: "tmux-previous-alert-window" },
  { id: "tmux-resize-pane-up", title: "^b, C-↑", detail: "窗格向上缩放 1 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-up" },
  { id: "tmux-resize-pane-down", title: "^b, C-↓", detail: "窗格向下缩放 1 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-down" },
  { id: "tmux-resize-pane-left", title: "^b, C-←", detail: "窗格向左缩放 1 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-left" },
  { id: "tmux-resize-pane-right", title: "^b, C-→", detail: "窗格向右缩放 1 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-right" },
  { id: "tmux-resize-pane-5-up", title: "^b, M-↑", detail: "窗格向上缩放 5 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-5-up" },
  { id: "tmux-resize-pane-5-down", title: "^b, M-↓", detail: "窗格向下缩放 5 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-5-down" },
  { id: "tmux-resize-pane-5-left", title: "^b, M-←", detail: "窗格向左缩放 5 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-5-left" },
  { id: "tmux-resize-pane-5-right", title: "^b, M-→", detail: "窗格向右缩放 5 格", groupId: "tmux", kind: "terminal", value: "tmux-resize-pane-5-right" },
  { id: "command-tmuxctl", title: "tmuxctl", detail: "tmux 会话管理", groupId: "tmux", kind: "send", value: "tmuxctl" },
  { id: "command-s", title: "S", detail: "启动或切换 Session", groupId: "tmux", kind: "send", value: "S" },
];

const DEFAULT_CODEX_SHORTCUTS: readonly ShortcutSeed[] = [
  { id: "command-proxyctl", title: "proxyctl", detail: "代理开关和状态", groupId: "codex", kind: "send", value: "proxyctl" },
  { id: "command-jump", title: "jump", detail: "目录跳转", groupId: "codex", kind: "send", value: "jump" },
  { id: "codex-ide", title: "/ide", detail: "加入 IDE 上下文", groupId: "codex", kind: "send", value: "/ide" },
  { id: "codex-keymap", title: "/keymap", detail: "配置 TUI 快捷键", groupId: "codex", kind: "send", value: "/keymap" },
  { id: "codex-vim", title: "/vim", detail: "切换 Vim 输入模式", groupId: "codex", kind: "send", value: "/vim" },
  { id: "codex-setup-default-sandbox", title: "/setup-default-sandbox", detail: "配置增强沙箱", groupId: "codex", kind: "send", value: "/setup-default-sandbox" },
  { id: "codex-experimental", title: "/experimental", detail: "实验功能", groupId: "codex", kind: "send", value: "/experimental" },
  { id: "codex-approve", title: "/approve", detail: "批准一次自动复核重试", groupId: "codex", kind: "send", value: "/approve" },
  { id: "codex-memories", title: "/memories", detail: "配置记忆", groupId: "codex", kind: "send", value: "/memories" },
  { id: "codex-skills", title: "/skills", detail: "使用技能", groupId: "codex", kind: "send", value: "/skills" },
  { id: "codex-import", title: "/import", detail: "导入 Claude Code 配置", groupId: "codex", kind: "send", value: "/import" },
  { id: "codex-hooks", title: "/hooks", detail: "查看和管理 hooks", groupId: "codex", kind: "send", value: "/hooks" },
  { id: "codex-review", title: "/review", detail: "审查当前改动", groupId: "codex", kind: "send", value: "/review" },
  { id: "codex-rename", title: "/rename", detail: "重命名当前会话", groupId: "codex", kind: "send", value: "/rename" },
  { id: "codex-archive", title: "/archive", detail: "归档当前会话", groupId: "codex", kind: "send", value: "/archive" },
  { id: "codex-delete", title: "/delete", detail: "永久删除当前会话", groupId: "codex", kind: "send", value: "/delete", dangerous: true },
  { id: "codex-fork", title: "/fork", detail: "派生当前会话", groupId: "codex", kind: "send", value: "/fork" },
  { id: "codex-worktree", title: "/worktree", detail: "使用新 worktree", groupId: "codex", kind: "send", value: "/worktree" },
  { id: "codex-app", title: "/app", detail: "在桌面 App 中继续", groupId: "codex", kind: "send", value: "/app" },
  { id: "codex-init", title: "/init", detail: "创建 AGENTS.md", groupId: "codex", kind: "send", value: "/init" },
  { id: "codex-recap", title: "/recap", detail: "总结当前会话", groupId: "codex", kind: "send", value: "/recap" },
  { id: "codex-voice", title: "/voice", detail: "开始或停止语音", groupId: "codex", kind: "send", value: "/voice" },
  { id: "codex-goal", title: "/goal", detail: "设置或查看长期目标", groupId: "codex", kind: "send", value: "/goal" },
  { id: "codex-agents", title: "/agents", detail: "打开 Agent 中心", groupId: "codex", kind: "send", value: "/agents" },
  { id: "codex-side", title: "/side", detail: "开启旁支会话", groupId: "codex", kind: "send", value: "/side" },
  { id: "codex-btw", title: "/btw", detail: "开启临时旁支会话", groupId: "codex", kind: "send", value: "/btw" },
  { id: "codex-copy", title: "/copy", detail: "复制最近回复", groupId: "codex", kind: "send", value: "/copy" },
  { id: "codex-export", title: "/export", detail: "导出 Markdown", groupId: "codex", kind: "send", value: "/export" },
  { id: "codex-raw", title: "/raw", detail: "切换原始滚动模式", groupId: "codex", kind: "send", value: "/raw" },
  { id: "codex-tui", title: "/tui", detail: "选择下次启动的 TUI 模式", groupId: "codex", kind: "send", value: "/tui" },
  { id: "codex-mention", title: "/mention", detail: "引用文件", groupId: "codex", kind: "send", value: "/mention" },
  { id: "codex-daemon", title: "/daemon", detail: "管理后台服务", groupId: "codex", kind: "send", value: "/daemon" },
  { id: "codex-cd", title: "/cd", detail: "切换工作目录", groupId: "codex", kind: "send", value: "/cd" },
  { id: "codex-pwd", title: "/pwd", detail: "查看当前目录", groupId: "codex", kind: "send", value: "/pwd" },
  { id: "codex-cwd", title: "/cwd", detail: "查看当前目录别名", groupId: "codex", kind: "send", value: "/cwd" },
  { id: "codex-usage", title: "/usage", detail: "查看用量", groupId: "codex", kind: "send", value: "/usage" },
  { id: "codex-debug-config", title: "/debug-config", detail: "查看配置来源", groupId: "codex", kind: "send", value: "/debug-config" },
  { id: "codex-title", title: "/title", detail: "配置终端标题", groupId: "codex", kind: "send", value: "/title" },
  { id: "codex-statusline", title: "/statusline", detail: "配置状态栏", groupId: "codex", kind: "send", value: "/statusline" },
  { id: "codex-theme", title: "/theme", detail: "选择高亮主题", groupId: "codex", kind: "send", value: "/theme" },
  { id: "codex-pets", title: "/pets", detail: "配置终端宠物", groupId: "codex", kind: "send", value: "/pets" },
  { id: "codex-pet", title: "/pet", detail: "终端宠物别名", groupId: "codex", kind: "send", value: "/pet" },
  { id: "codex-mcp", title: "/mcp", detail: "查看 MCP 工具", groupId: "codex", kind: "send", value: "/mcp" },
  { id: "codex-apps", title: "/apps", detail: "管理应用", groupId: "codex", kind: "send", value: "/apps" },
  { id: "codex-plugins", title: "/plugins", detail: "浏览插件", groupId: "codex", kind: "send", value: "/plugins" },
  { id: "codex-logout", title: "/logout", detail: "退出登录", groupId: "codex", kind: "send", value: "/logout", dangerous: true },
  { id: "codex-quit", title: "/quit", detail: "退出 Codex", groupId: "codex", kind: "send", value: "/quit", dangerous: true },
  { id: "codex-exit", title: "/exit", detail: "退出 Codex 别名", groupId: "codex", kind: "send", value: "/exit", dangerous: true },
  { id: "codex-feedback", title: "/feedback", detail: "发送日志反馈", groupId: "codex", kind: "send", value: "/feedback" },
  { id: "codex-ps", title: "/ps", detail: "查看后台终端", groupId: "codex", kind: "send", value: "/ps" },
  { id: "codex-stop", title: "/stop", detail: "停止后台终端", groupId: "codex", kind: "send", value: "/stop" },
  { id: "codex-clean", title: "/clean", detail: "/stop 的别名", groupId: "codex", kind: "send", value: "/clean" },
  { id: "codex-clear", title: "/clear", detail: "清屏并开始新会话", groupId: "codex", kind: "send", value: "/clear", dangerous: true },
  { id: "codex-subagents", title: "/subagents", detail: "切换当前会话的子 Agent", groupId: "codex", kind: "send", value: "/subagents" },
  { id: "codex-key-transcript", title: "Ctrl+T", detail: "打开会话 transcript", groupId: "codex", kind: "sequence", value: "Ctrl+T" },
  { id: "codex-key-find", title: "F3", detail: "搜索 transcript", groupId: "codex", kind: "sequence", value: "F3" },
  { id: "codex-key-activity", title: "F4", detail: "查看活动详情", groupId: "codex", kind: "sequence", value: "F4" },
  { id: "codex-key-warnings", title: "F2", detail: "查看警告", groupId: "codex", kind: "sequence", value: "F2" },
  { id: "codex-key-editor", title: "Ctrl+G", detail: "用外部编辑器编辑输入", groupId: "codex", kind: "sequence", value: "Ctrl+G" },
  { id: "codex-key-copy", title: "Ctrl+O", detail: "复制最近回复", groupId: "codex", kind: "sequence", value: "Ctrl+O" },
  { id: "codex-key-clear", title: "Ctrl+L", detail: "清空终端显示", groupId: "codex", kind: "sequence", value: "Ctrl+L" },
  { id: "codex-key-raw", title: "Alt+R", detail: "切换原始滚动模式", groupId: "codex", kind: "sequence", value: "Alt+R" },
  { id: "codex-key-voice", title: "F8", detail: "开始或停止语音", groupId: "codex", kind: "sequence", value: "F8" },
  { id: "codex-key-voice-mute", title: "Ctrl+X", detail: "切换语音静音", groupId: "codex", kind: "sequence", value: "Ctrl+X" },
  { id: "codex-key-reasoning-down", title: "Alt+,", detail: "降低推理强度", groupId: "codex", kind: "sequence", value: "Alt+," },
  { id: "codex-key-reasoning-up", title: "Alt+.", detail: "提高推理强度", groupId: "codex", kind: "sequence", value: "Alt+." },
  { id: "codex-key-edit-queued", title: "Shift+←", detail: "编辑上一条排队消息", groupId: "codex", kind: "sequence", value: "Shift+Left" },
  { id: "codex-key-edit-queued-alt", title: "Alt+↑", detail: "编辑上一条排队消息", groupId: "codex", kind: "sequence", value: "Alt+Up" },
  { id: "codex-key-prompt-back", title: "Shift+→", detail: "返回输入区域", groupId: "codex", kind: "sequence", value: "Shift+Right" },
  { id: "codex-key-prompt-back-alt", title: "Alt+↓", detail: "返回输入区域", groupId: "codex", kind: "sequence", value: "Alt+Down" },
  { id: "codex-key-skip-question", title: "Ctrl+]", detail: "跳过当前问题", groupId: "codex", kind: "sequence", value: "Ctrl+]" },
  { id: "codex-key-toggle-shortcuts", title: "?", detail: "打开快捷键提示", groupId: "codex", kind: "sequence", value: "?" },
  { id: "codex-key-history-previous", title: "Ctrl+R", detail: "历史记录上一项", groupId: "codex", kind: "sequence", value: "Ctrl+R" },
  { id: "codex-key-history-next", title: "Ctrl+S", detail: "历史记录下一项", groupId: "codex", kind: "sequence", value: "Ctrl+S" },
  { id: "codex-key-newline", title: "Ctrl+J", detail: "输入换行", groupId: "codex", kind: "sequence", value: "Ctrl+J" },
  { id: "codex-key-newline-cr", title: "Ctrl+M", detail: "输入换行别名", groupId: "codex", kind: "sequence", value: "Ctrl+M" },
  { id: "codex-key-exit", title: "Ctrl+D", detail: "退出 Codex", groupId: "codex", kind: "sequence", value: "Ctrl+D", dangerous: true },
  { id: "codex-key-paste-image", title: "Ctrl+V", detail: "粘贴图片", groupId: "codex", kind: "sequence", value: "Ctrl+V" },
  { id: "codex-key-mode", title: "Shift+Tab", detail: "切换协作模式", groupId: "codex", kind: "sequence", value: "Shift+Tab" },
  { id: "codex-key-agent-previous", title: "Alt+←", detail: "上一个 Agent", groupId: "codex", kind: "sequence", value: "Alt+Left" },
  { id: "codex-key-agent-next", title: "Alt+→", detail: "下一个 Agent", groupId: "codex", kind: "sequence", value: "Alt+Right" },
  { id: "codex-key-kill-line-start", title: "Ctrl+U", detail: "删除到行首", groupId: "codex", kind: "sequence", value: "Ctrl+U" },
  { id: "codex-key-kill-line-end", title: "Ctrl+K", detail: "删除到行尾", groupId: "codex", kind: "sequence", value: "Ctrl+K" },
  { id: "codex-key-yank", title: "Ctrl+Y", detail: "粘贴已删除文本", groupId: "codex", kind: "sequence", value: "Ctrl+Y" },
];

export const DEFAULT_SHORTCUTS: readonly ShortcutSeed[] = [
  { id: "favorite-git-status", title: "git status", detail: "工作区状态", groupId: "favorites", kind: "send", value: "git status" },
  { id: "favorite-git-diff", title: "git diff", detail: "查看改动", groupId: "favorites", kind: "send", value: "git diff" },
  { id: "favorite-pwd", title: "pwd", detail: "当前目录", groupId: "favorites", kind: "send", value: "pwd" },
  { id: "favorite-ls", title: "ls", detail: "列出文件", groupId: "favorites", kind: "send", value: "ls" },
  { id: "favorite-clear", title: "clear", detail: "清屏", groupId: "favorites", kind: "send", value: "clear" },
  { id: "favorite-git-log", title: "git log", detail: "最近提交", groupId: "favorites", kind: "send", value: "git log --oneline -5" },
  { id: "favorite-npm-test", title: "npm test", detail: "运行测试", groupId: "favorites", kind: "send", value: "npm test" },
  { id: "favorite-git-branch", title: "git branch", detail: "当前分支", groupId: "favorites", kind: "send", value: "git branch --show-current" },
  { id: "tmux-new", title: "^b, c", detail: "new win", groupId: "tmux", kind: "terminal", value: "tmux-new-window" },
  { id: "tmux-next", title: "^b, n", detail: "next", groupId: "tmux", kind: "terminal", value: "tmux-next-window" },
  { id: "tmux-previous", title: "^b, p", detail: "prev win", groupId: "tmux", kind: "terminal", value: "tmux-previous-window" },
  { id: "tmux-detach", title: "^b, d", detail: "detach", groupId: "tmux", kind: "terminal", value: "tmux-detach" },
  { id: "tmux-window-list", title: "^b, w", detail: "windows", groupId: "tmux", kind: "terminal", value: "tmux-window-list" },
  { id: "tmux-zoom", title: "^b, z", detail: "zoom", groupId: "tmux", kind: "terminal", value: "tmux-zoom-pane" },
  { id: "tmux-window-1", title: "^b, 1", detail: "window 1", groupId: "tmux", kind: "terminal", value: "tmux-window-1" },
  { id: "tmux-window-2", title: "^b, 2", detail: "window 2", groupId: "tmux", kind: "terminal", value: "tmux-window-2" },
  ...DEFAULT_TMUX_SHORTCUTS,
  { id: "codex-new", title: "/new", detail: "fresh", groupId: "codex", kind: "send", value: "/new" },
  { id: "codex-compact", title: "/compact", detail: "context", groupId: "codex", kind: "send", value: "/compact" },
  { id: "codex-model", title: "/model", detail: "switch", groupId: "codex", kind: "send", value: "/model" },
  { id: "codex-permissions", title: "/permissions", detail: "access", groupId: "codex", kind: "send", value: "/permissions" },
  { id: "codex-plan", title: "/plan", detail: "design", groupId: "codex", kind: "send", value: "/plan" },
  { id: "codex-resume", title: "/resume", detail: "continue", groupId: "codex", kind: "send", value: "/resume" },
  { id: "codex-diff", title: "/diff", detail: "changes", groupId: "codex", kind: "send", value: "/diff" },
  { id: "codex-status", title: "/status", detail: "usage", groupId: "codex", kind: "send", value: "/status" },
  ...DEFAULT_CODEX_SHORTCUTS,
  { id: "key-escape", title: "Esc", detail: "cancel", groupId: "ctrl", kind: "terminal", value: "codex-escape" },
  { id: "key-enter", title: "↵", detail: "enter", groupId: "ctrl", kind: "terminal", value: "codex-enter" },
  { id: "key-tab", title: "Tab", detail: "complete", groupId: "ctrl", kind: "terminal", value: "codex-tab" },
  { id: "key-up", title: "↑", detail: "up", groupId: "ctrl", kind: "terminal", value: "codex-up" },
  { id: "key-down", title: "↓", detail: "down", groupId: "ctrl", kind: "terminal", value: "codex-down" },
  { id: "key-left", title: "←", detail: "left", groupId: "ctrl", kind: "terminal", value: "codex-left" },
  { id: "key-right", title: "→", detail: "right", groupId: "ctrl", kind: "terminal", value: "codex-right" },
  { id: "ctrl-c", title: "^C", detail: "stop", groupId: "ctrl", kind: "terminal", value: "codex-interrupt", dangerous: true },
  { id: "keyboard-prefix", title: "^B", detail: "tmux prefix", groupId: "keyboard", kind: "sequence", value: "^B" },
  { id: "keyboard-escape", title: "esc", detail: "escape", groupId: "keyboard", kind: "sequence", value: "Esc" },
  { id: "keyboard-enter", title: "↵", detail: "enter", groupId: "keyboard", kind: "sequence", value: "Enter" },
  { id: "keyboard-tab", title: "tab", detail: "tab", groupId: "keyboard", kind: "sequence", value: "Tab" },
  { id: "keyboard-shift-tab", title: "shift tab", detail: "previous", groupId: "keyboard", kind: "sequence", value: "Shift+Tab" },
  { id: "keyboard-up", title: "↑", detail: "up", groupId: "keyboard", kind: "sequence", value: "ArrowUp" },
  { id: "keyboard-down", title: "↓", detail: "down", groupId: "keyboard", kind: "sequence", value: "ArrowDown" },
  { id: "keyboard-left", title: "←", detail: "left", groupId: "keyboard", kind: "sequence", value: "ArrowLeft" },
  { id: "keyboard-right", title: "→", detail: "right", groupId: "keyboard", kind: "sequence", value: "ArrowRight" },
  { id: "keyboard-home", title: "home", detail: "line start", groupId: "keyboard", kind: "sequence", value: "Home" },
  { id: "keyboard-end", title: "end", detail: "line end", groupId: "keyboard", kind: "sequence", value: "End" },
  { id: "keyboard-delete", title: "del", detail: "delete", groupId: "keyboard", kind: "sequence", value: "Delete" },
  { id: "keyboard-insert", title: "ins", detail: "insert", groupId: "keyboard", kind: "sequence", value: "Insert" },
  { id: "keyboard-page-up", title: "pgUp", detail: "page up", groupId: "keyboard", kind: "sequence", value: "PageUp" },
  { id: "keyboard-page-down", title: "pgDn", detail: "page down", groupId: "keyboard", kind: "sequence", value: "PageDown" },
  ...Array.from({ length: 12 }, (_, index) => ({
    id: `keyboard-f${index + 1}`,
    title: `F${index + 1}`,
    detail: "function",
    groupId: "keyboard",
    kind: "sequence" as const,
    value: `F${index + 1}`,
  })),
  { id: "keyboard-question", title: "?", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "?" },
  { id: "keyboard-slash", title: "/", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "/" },
  { id: "keyboard-pipe", title: "|", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "|" },
  { id: "keyboard-tilde", title: "~", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "~" },
  { id: "keyboard-dash", title: "-", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "-" },
  { id: "keyboard-underscore", title: "_", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "_" },
  { id: "keyboard-equals", title: "=", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "=" },
  { id: "keyboard-colon", title: ":", detail: "symbol", groupId: "keyboard", kind: "sequence", value: ":" },
  { id: "keyboard-semicolon", title: ";", detail: "symbol", groupId: "keyboard", kind: "sequence", value: ";" },
  { id: "keyboard-open-brace", title: "{", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "{" },
  { id: "keyboard-close-brace", title: "}", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "}" },
  { id: "keyboard-open-bracket", title: "[", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "[" },
  { id: "keyboard-close-bracket", title: "]", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "]" },
  { id: "keyboard-at", title: "@", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "@" },
  { id: "keyboard-percent", title: "%", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "%" },
  { id: "keyboard-caret", title: "^", detail: "symbol", groupId: "keyboard", kind: "sequence", value: "^" },
  { id: "composer-attachment", title: "附件", detail: "选择文件", groupId: "composer", kind: "insert", value: "", actionKey: "attachment", displayMode: "closed", sortOrder: 0 },
  { id: "composer-close-panel", title: "关闭", detail: "关闭快捷栏", groupId: "composer", kind: "insert", value: "", actionKey: "close-panel", displayMode: "expanded", sortOrder: 0 },
  { id: "composer-scroll-top", title: "顶部", detail: "滚动到顶部", groupId: "composer", kind: "insert", value: "", actionKey: "scroll-top", displayMode: "both", sortOrder: 1 },
  { id: "composer-scroll-bottom", title: "底部", detail: "滚动到底部", groupId: "composer", kind: "insert", value: "", actionKey: "scroll-bottom", displayMode: "both", sortOrder: 2 },
  { id: "composer-session-files", title: "文件", detail: "浏览 Session 文件", groupId: "composer", kind: "insert", value: "", actionKey: "session-files", displayMode: "both", sortOrder: 3 },
  { id: "composer-debug-log", title: "日志", detail: "收集调试日志", groupId: "composer", kind: "insert", value: "", actionKey: "debug-log", displayMode: "both", sortOrder: 4 },
  { id: "composer-scroll-export", title: "导出", detail: "导出滚动日志", groupId: "composer", kind: "insert", value: "", actionKey: "scroll-export", displayMode: "both", sortOrder: 5 },
  { id: "composer-escape", title: "Esc", detail: "cancel", groupId: "composer", kind: "terminal", value: "codex-escape", actionKey: "terminal-escape", displayMode: "both", sortOrder: 6 },
  { id: "composer-up", title: "↑", detail: "上一条输入", groupId: "composer", kind: "terminal", value: "codex-up", actionKey: "terminal-up", displayMode: "both", sortOrder: 7 },
  { id: "composer-down", title: "↓", detail: "下一条输入", groupId: "composer", kind: "terminal", value: "codex-down", actionKey: "terminal-down", displayMode: "both", sortOrder: 8 },
  { id: "composer-enter", title: "↵", detail: "回车", groupId: "composer", kind: "terminal", value: "codex-enter", actionKey: "terminal-enter", displayMode: "both", sortOrder: 9 },
  { id: "composer-keyboard-panel", title: "键盘", detail: "打开键盘面板", groupId: "composer", kind: "insert", value: "", actionKey: "keyboard-panel", displayMode: "closed", sortOrder: 10 },
  { id: "composer-ctrl-panel", title: "Ctrl", detail: "打开 Ctrl 面板", groupId: "composer", kind: "insert", value: "", actionKey: "ctrl-panel", displayMode: "expanded", sortOrder: 11 },
];
